services:
  - type: web
    name: barbershop
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn barbershop.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com,barbershop.pro,www.barbershop.pro
      - key: SECURE_SSL_REDIRECT
        value: true
    autoDeploy: true